name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      # https://mcr.microsoft.com/en-us/artifact/mar/playwright/tags
      # https://playwright.dev/docs/ci#via-containers
      image: mcr.microsoft.com/playwright:v1.50.1-noble

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build the adapter
        run: pnpm build

      - name: Build all workers
        run: pnpm -r build:worker

      - name: Run playwright tests
        run: pnpm e2e

      - name: Run playwright dev tests
        run: pnpm e2e:dev

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: ./**/playwright-report
          retention-days: 1
